# Generated by Django 5.2.4 on 2025-08-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('category_image', models.ImageField(null=True, upload_to='category_image/')),
            ],
        ),
    ]
