# Generated by Django 5.2.4 on 2025-08-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_order_total_qauntity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_qauntity',
            new_name='total_quantity',
        ),
    ]
