# Generated by Django 5.2.4 on 2025-08-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_cart_disc_price_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='disc_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
