# Generated by Django 5.2.4 on 2025-08-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_alter_address_address_alter_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='platform_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
