# Generated by Django 5.2.4 on 2025-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='disc_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='disc_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
