# Generated by Django 5.2.4 on 2025-08-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_wishlist_disc_percent_wishlist_disc_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
