# Generated by Django 5.2.4 on 2025-08-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_address_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
