# Generated by Django 5.2.4 on 2025-08-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_cart_offer_discount_cart_platform_fee_cart_shipping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='offer_discount',
            new_name='final_total',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total_amount',
            new_name='total_discount',
        ),
    ]
