# Generated by Django 5.2.4 on 2025-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0011_remove_cart_added_on_remove_cart_disc_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
