# Generated by Django 5.2.4 on 2025-08-05 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('sub_cat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_cat_name', models.CharField(max_length=20)),
                ('sub_cat_image', models.ImageField(null=True, upload_to='sub_cat_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category_app.category')),
            ],
        ),
    ]
