# Generated by Django 5.2.4 on 2025-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_items_image_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_qauntity',
            field=models.IntegerField(default=0),
        ),
    ]
