# Generated by Django 5.2.4 on 2025-08-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0007_alter_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded')], default='pending', max_length=25),
        ),
    ]
