# Generated by Django 5.2.4 on 2025-08-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0008_order_items_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=20),
        ),
    ]
