# Generated by Django 5.2.4 on 2025-08-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0010_alter_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=25),
        ),
    ]
