# Generated by Django 5.2.4 on 2025-08-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0011_alter_order_items_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='return_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Requested', 'Not Requested'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded')], default='Not Requested', max_length=20),
        ),
    ]
