# Generated by Django 5.2.4 on 2025-08-24 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0012_order_items_return_requested_and_more'),
        ('product_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='product',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('cancel_status', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Not Requested', max_length=20)),
                ('refund_status', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Refunded', 'Refunded')], default='Not Requested', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_app.products')),
            ],
        ),
        migrations.CreateModel(
            name='CancelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel_requests', to='order_app.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Partially Refunded', 'Partially Refunded'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('payment_mode', models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('refund_status', models.CharField(choices=[('Not Requested', 'Not Requested'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Refunded', 'Refunded')], default='Not Requested', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.orders'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='order_app.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_items',
        ),
    ]
